services:
  db:
    image: postgres:13
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Guinho@01
      POSTGRES_DB: products_apirest
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d


  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: Guinho@01
      DB_NAME: products_apirest