services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Guinho@01
      POSTGRES_DB: products_apirest
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d
