// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type Product struct {
	ID        int32     `json:"id"`
	Nome      string    `json:"nome"`
	Descricao string    `json:"descricao"`
	Preco     string    `json:"preco"`
	DataVenda time.Time `json:"data_venda"`
}
